import { ABI } from '../utils/types';

// NOTE: Does not include ERC20 standard functions and events
export default ([
    {
       "name":"Swap",
       "type":"event",
       "inputs":[
          {
             "name":"sender",
             "type":"address",
             "indexed":true,
             "internalType":"address"
          },
          {
             "name":"amount0In",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          },
          {
             "name":"amount1In",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          },
          {
             "name":"amount0Out",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          },
          {
             "name":"amount1Out",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          },
          {
             "name":"to",
             "type":"address",
             "indexed":true,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "name":"Sync",
       "type":"event",
       "inputs":[
          {
             "name":"reserve0",
             "type":"uint112",
             "indexed":false,
             "internalType":"uint112"
          },
          {
             "name":"reserve1",
             "type":"uint112",
             "indexed":false,
             "internalType":"uint112"
          }
       ],
       "anonymous":false
    },
    {
       "name":"DOMAIN_SEPARATOR",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"",
             "type":"bytes32",
             "internalType":"bytes32"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    },
    {
       "name":"MINIMUM_LIQUIDITY",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"",
             "type":"uint256",
             "internalType":"uint256"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    },
    {
       "name":"PERMIT_TYPEHASH",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"",
             "type":"bytes32",
             "internalType":"bytes32"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    },
    {
       "name":"factory",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"",
             "type":"address",
             "internalType":"address"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    },
    {
       "name":"getReserves",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"_reserve0",
             "type":"uint112",
             "internalType":"uint112"
          },
          {
             "name":"_reserve1",
             "type":"uint112",
             "internalType":"uint112"
          },
          {
             "name":"_blockTimestampLast",
             "type":"uint32",
             "internalType":"uint32"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    },
    {
       "name":"initialize",
       "type":"function",
       "inputs":[
          {
             "name":"_token0",
             "type":"address",
             "internalType":"address"
          },
          {
             "name":"_token1",
             "type":"address",
             "internalType":"address"
          }
       ],
       "outputs":[
          
       ],
       "payable":false,
       "constant":false,
       "stateMutability":"nonpayable"
    },
    {
       "name":"kLast",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"",
             "type":"uint256",
             "internalType":"uint256"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    },
    {
       "name":"nonces",
       "type":"function",
       "inputs":[
          {
             "name":"",
             "type":"address",
             "internalType":"address"
          }
       ],
       "outputs":[
          {
             "name":"",
             "type":"uint256",
             "internalType":"uint256"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    },
    {
       "name":"permit",
       "type":"function",
       "inputs":[
          {
             "name":"owner",
             "type":"address",
             "internalType":"address"
          },
          {
             "name":"spender",
             "type":"address",
             "internalType":"address"
          },
          {
             "name":"value",
             "type":"uint256",
             "internalType":"uint256"
          },
          {
             "name":"deadline",
             "type":"uint256",
             "internalType":"uint256"
          },
          {
             "name":"v",
             "type":"uint8",
             "internalType":"uint8"
          },
          {
             "name":"r",
             "type":"bytes32",
             "internalType":"bytes32"
          },
          {
             "name":"s",
             "type":"bytes32",
             "internalType":"bytes32"
          }
       ],
       "outputs":[
          
       ],
       "payable":false,
       "constant":false,
       "stateMutability":"nonpayable"
    },
    {
       "name":"price0CumulativeLast",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"",
             "type":"uint256",
             "internalType":"uint256"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    },
    {
       "name":"price1CumulativeLast",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"",
             "type":"uint256",
             "internalType":"uint256"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    },
    {
       "name":"skim",
       "type":"function",
       "inputs":[
          {
             "name":"to",
             "type":"address",
             "internalType":"address"
          }
       ],
       "outputs":[
          
       ],
       "payable":false,
       "constant":false,
       "stateMutability":"nonpayable"
    },
    {
       "name":"swap",
       "type":"function",
       "inputs":[
          {
             "name":"amount0Out",
             "type":"uint256",
             "internalType":"uint256"
          },
          {
             "name":"amount1Out",
             "type":"uint256",
             "internalType":"uint256"
          },
          {
             "name":"to",
             "type":"address",
             "internalType":"address"
          },
          {
             "name":"data",
             "type":"bytes",
             "internalType":"bytes"
          }
       ],
       "outputs":[
          
       ],
       "payable":false,
       "constant":false,
       "stateMutability":"nonpayable"
    },
    {
       "name":"sync",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          
       ],
       "payable":false,
       "constant":false,
       "stateMutability":"nonpayable"
    },
    {
       "name":"token0",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"",
             "type":"address",
             "internalType":"address"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    },
    {
       "name":"token1",
       "type":"function",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"",
             "type":"address",
             "internalType":"address"
          }
       ],
       "payable":false,
       "constant":true,
       "stateMutability":"view"
    }
] as ABI);